// Code generated by counterfeiter. DO NOT EDIT.
package refresherfakes

import (
	"sync"

	watcher "github.com/hcjulz/damon/refresher"
)

type FakeRefreshFunc struct {
	Stub        func()
	mutex       sync.RWMutex
	argsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRefreshFunc) Spy() {
	fake.mutex.Lock()
	fake.argsForCall = append(fake.argsForCall, struct {
	}{})
	stub := fake.Stub
	fake.recordInvocation("RefreshFunc", []interface{}{})
	fake.mutex.Unlock()
	if stub != nil {
		fake.Stub()
	}
}

func (fake *FakeRefreshFunc) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeRefreshFunc) Calls(stub func()) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeRefreshFunc) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRefreshFunc) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ watcher.RefreshFunc = new(FakeRefreshFunc).Spy
