// Code generated by counterfeiter. DO NOT EDIT.
package componentfakes

import (
	"sync"

	"github.com/hcjulz/damon/component"
)

type FakeDoneModalFunc struct {
	Stub        func(int, string)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 int
		arg2 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDoneModalFunc) Spy(arg1 int, arg2 string) {
	fake.mutex.Lock()
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 int
		arg2 string
	}{arg1, arg2})
	stub := fake.Stub
	fake.recordInvocation("DoneModalFunc", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if stub != nil {
		fake.Stub(arg1, arg2)
	}
}

func (fake *FakeDoneModalFunc) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeDoneModalFunc) Calls(stub func(int, string)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeDoneModalFunc) ArgsForCall(i int) (int, string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *FakeDoneModalFunc) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDoneModalFunc) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ component.DoneModalFunc = new(FakeDoneModalFunc).Spy
