url_docker_image_dockerhub = "https://hub.docker.com/r/hashicorp/damon"
url_source_repository      = "https://github.com/hashicorp/damon"
url_project_website        = "https://github.com/hashicorp/damon"
url_license                = "https://github.com/hashicorp/damon/blob/main/LICENSE"
url_release_notes          = "https://github.com/hashicorp/damon"